#!/usr/bin/env bash

publish() {
  build
  npm publish
  cnpm sync @gutenye/react-svg-loader
  git commit -am 'publish'
  git push
}

build() {
  npm run build
}

case "$1" in
  build ) build ;;
esac
