#!/usr/bin/env bash

main() {
  babel src --out-dir lib --copy-files -w
}

publish() {
  build
  npm publish --registry=https://registry.npmjs.org
  cnpm sync @gutenye/react-svg-loader
  git commit -am 'publish'
  git push
}

build() {
  npm run build
}

case "$1" in
  "" ) main ;;
  build ) build ;;
  publish ) publish ;;
esac
